### ISSUE TITLE
Recurring crash from a multiblock

### ISSUE THREAD

**Issue by felix-schneider** [GregTechCEu/GregTech#1566] opened 2023-03-05 15:21 UTC
### GregTech CEu Version

v2.5.2-beta

### Modpack Used

Nomifactory GTCEu 1.51

### Addons Installed

GregicalityMultiblocks 1.1.6

### Environment

Singleplayer

### Side Crashed

Server

### New Worlds

Unsure

### Steps to Reproduce

Unpredictable. Possibly related to a craft starting in a multiblock?

I wasn't doing anything in particular, but the same crash has happened multiple times.

### Crash Report

https://gist.github.com/felix-schneider/1f703afaefd5b1f7e83dcd91cecbbb5d

### Additional Information

The machine at the specified coordinates is an EBF. It is passively crafting part of the platline: Sodium Peroxide + Iridium Metal Residue = Iridium Dioxide Residue + Sodium.
It has no fluid input or output hatches, just buses. But it mostly seems to run fine.

**Comment by YiRanMushroom** [comment] 2023-03-06 10:52
Yes it is occuring occatioanally, I had posted the issue days ago but been closed due to concidering it was caused by another addon. It seems that all multiblocks can cause this issue even if they are not working currently.

**Comment by YiRanMushroom** [comment] 2023-03-06 10:54
I am sure that we meet the same problem because mine crash report is familiar with yours, maybe we should post the issue in GregicalityMultiblocks.

**Comment by ghzdude** [comment] 2023-03-06 10:55
this may be fixed with #1522 (and the CEu 2.5.3 update)

**Comment by YiRanMushroom** [comment] 2023-03-06 13:23
No, it hasn't been fixed yet.

**Closed** 2023-03-09 03:39 UTC
Labels: status: unverified
