### ISSUE TITLE
yes it crash again

### ISSUE THREAD

**Issue by DAmanc123** [GregTechCEu/GregTech#1234] opened 2022-10-25 07:16 UTC
### GregTech CEu Version

2.4.1

### Modpack Used

no

### Addons Installed

no

### Environment

serevtr

### Side Crashed

Server

### New Worlds

No

### Steps to Reproduce

nothing

### Crash Report

[Uploading crash-2022-10-25_15.03.23-server.txt…]()

**Comment by htmlcsjs** [comment] 2022-10-25 07:21
duplicate of #1169, also your crash report is broken

**Closed by htmlcsjs** 2022-10-25 07:21 UTC
Labels: status: unverified

**Comment by Syrcan** [comment] 2022-10-25 07:23
```
    # If enabled, recipes of the corresponding NC machine will also be added for GTCE machines. Order: Manufactory, Separator, Decay Hastener, Fuel Reprocessor, Alloy Furnace, Fluid Infuser, Melter, Supercooler, Electrolyzer, Assembler, Ingot Former, Pressurizer, Chemical Reactor, Fluid Mixer, Crystallizer, Fluid Enricher, Fluid Extractor, Centrifuge, Rock Crusher.
    B:gtce_recipe_integration <
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
        true
     >
```
This is what most likely is in your `nuclearcraft.cfg` file. Please change these to false to fix the crash.

**Comment by DAmanc123** [comment] 2022-10-25 07:24
wait a sec

**Comment by DAmanc123** [comment] 2022-10-25 08:06
thank you,it runs good now
