### ISSUE TITLE
With NuclearСraft I get a game crash

### ISSUE THREAD

**Issue by JourneyIM** [GregTechCEu/GregTech#1313] opened 2022-12-03 10:37 UTC
### GregTech CEu Version

2.4.4

### Modpack Used

My private modpack

### Addons Installed

GregicalityMultiblocks 1.1.5, ULV Covers 0.2.2, DevTech 2.1.2, Gregtech Food Option 1.8.1

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

No

### Steps to Reproduce

Just start Game

### Crash Report

https://mclo.gs/5NH07O0

### Additional Information

The error occurs on a standart NuclearCraft

**Comment by htmlcsjs** [comment] 2022-12-03 11:06
duplicate of #1169

**Closed by htmlcsjs** 2022-12-03 11:06 UTC
Labels: status: unverified
