### ISSUE TITLE
Tooltips for Turbine Blades are broken

### ISSUE THREAD

**Issue by yuu-electrum** [GregTechCEu/GregTech#1491] opened 2023-02-10 16:11 UTC
### GregTech CEu Version

2.5.0

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Yes

### Expected Behavior

The tooltip should show blades' properties properly.

### Actual Behavior

![2023-02-11_01 01 38](https://user-images.githubusercontent.com/14097114/218138785-33f38bd2-5c0c-4bff-ba2f-83df20d8a30a.png)
The tooltip shows an error on Blades made out of some materials.
Here's also an log that sensitive data are masked.

[debug.log](https://github.com/GregTechCEu/GregTech/files/10709220/debug.log)

### Steps to Reproduce

1. Search for recipes of any Blade on JEI.
2. Click other sort of it and hover on them.

### Additional Information

Mod installed for confirmation:

 - Forge 2860
 - GregTech CEu 2.5.0-beta
 - CodeChicken Lib 3.2.3.358
 - Just Enough Items 4.16.1.301

**Comment by TechLord22** [comment] 2023-02-11 00:22
Closing as duplicate of #1433. It is also fixed as of GTCEu 2.5.1, in #1408.

**Closed by TechLord22** 2023-02-11 00:22 UTC
Labels: status: unverified
