### ISSUE TITLE
Gregtech crashes with Nuclearcraft 

### ISSUE THREAD

**Issue by slebreton79** [GregTechCEu/GregTech#2642] opened 2024-10-19 01:39 UTC
### GregTech CEu Version

2.8.10-beta

### Modpack Used

Non

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

add latest version of nuclear craft (NuclearCraft-2.18zzz-1.12.2.jar)
start Minecraft and then crashes.

### Crash Report

latest.log 
https://pastebin.com/87jHWM2c
crash report
https://pastebin.com/BMz6HtPg

**Comment by ghzdude** [comment] 2024-10-19 01:40
disable NC's recipe integration in their configs, as they're designed for GTCE and not CEu

**Comment by ghzdude** [comment] 2024-10-19 01:42
also duplicate of #2454

**Closed by ghzdude** 2024-10-19 01:42 UTC
Labels: status: unverified
