### ISSUE TITLE
[BUG] Energy Hatch Takes Power From ALL Sides

### ISSUE THREAD

**Issue by shawnbyday** [GregTechCEu/GregTech#1016] opened 2022-06-05 20:38 UTC
**Describe the bug**

**Versions**
Forge: 14.23.5.2860
GTCEu: 2.2.3-beta
_Modpack:_ Nomifactory 1.2.3 with GTCEu

**Setup**
_Does this issue happen on Singleplayer, a Server, or both_: Server

**Steps To Reproduce**
1) Can connect cable to any side of energy hatch. Will take power even if not connected to the input side.

**Expected behavior**
Expected to only be able to input power from one side.

**Comment by ALongStringOfNumbers** [comment] 2022-06-05 23:55
This is not a bug, but rather the intended behavior for energy input hatches.

**Comment by shawnbyday** [comment] 2022-06-06 00:06
Ok. You don't have to give me an explanation but if you have time for one, I'm curious as to why this is intended? It seems silly and explosionish.

**Comment by ghzdude** [comment] 2022-06-06 00:09
The current behavior is the same for busses and hatches, in that you can insert/extract from any side instead of only one face.

**Comment by nemo48rus** [comment] 2022-06-06 17:26
Thats not bug, that is feature!
Great feature.
Just dont clue 2 mechs with 1 interface. Thats easy.

**Comment by DStrand1** [comment] 2022-06-07 05:03
Closing this as not a bug

**Closed by DStrand1** 2022-06-07 05:03 UTC
Labels: status: unverified
