### ISSUE TITLE
[BUG] Crash when hovering over tall grass with a Drill

### ISSUE THREAD

**Issue by m2r1k5** [GregTechCEu/GregTech#332] opened 2021-12-12 11:10 UTC
**Describe the bug**
When looking at Tall grass with an electric drill, the game crashes.
This happens every time that world is loaded as well.

**Versions**
Forge: 14.23.5.2855
GTCE: build 0f26b39d2
Other mods: [filenames.txt](https://github.com/GregTechCEu/GregTech/files/7698612/filenames.txt)
**Setup**
Playing Solo

**Steps To Reproduce**
1) Load world
2) Get a drill
3) Hover over tall grass.
**Expected behavior**
Game should not crash

Log file:
[latest.log](https://github.com/GregTechCEu/GregTech/files/7698611/latest.log)

**Comment by ALongStringOfNumbers** [comment] 2021-12-18 19:46
This appears to be fixed, or at least I cannot reproduce this on the latest version of CEu

**Comment by ALongStringOfNumbers** [comment] 2022-01-28 19:06
I cannot reproduce this on the latest version of CEu, so I believe this might have been fixed with some other drill block outline related issues.

If you still have this issue on the latest version of CEu post here and this issue can be reopened.

**Closed by ALongStringOfNumbers** 2022-01-28 19:06 UTC
Labels: status: unverified, type: bug
